### ISSUE TITLE
Hello, I have some questions for you

### ISSUE THREAD

**Issue by YANKT** [Morilla123/Seizure_Prediction_ML#2]
I am a Grade 1 master 
![1648799881(1)](https://user-images.githubusercontent.com/48278536/161222326-99676ced-3760-40e7-b404-6a5e8f61256b.jpg)
student from China. I am studying epilepsy prediction. I have some questions to ask
1.‘’estable‘’ What does this file code do
2.The difference between‘’rnn_test"and "rnn-test"
3.“code_week4”What does it do
4.dfXX = pd.read_
![1648800011(1)](https://user-images.githubusercontent.com/48278536/161222361-8e878faa-d24e-493f-a715-3c5b4ff5774d.jpg)
![1648800206(1)](https://user-images.githubusercontent.com/48278536/161222395-39956d3d-3383-406c-8fdc-43fbd8d90608.jpg)
csv('chb01_XXc.csv')Where did this  'c'  file come from

**Comment by Morilla123** [comment]
Hi Hankt!

I am sorry for the impropriety of the document, I was starting to work with github and python.

Regarding the query, the dataset is on this page:
https://physionet.org/content/chbmit/1.0.0/

The files are in .edf format, to convert it to csv you have to use the mne library. function read_raw_edf(XXX.edf) then:
header = ','.join(edfXXX.ch_names)
dfXX = np.savetxt('new_name.csv', XXX.edf.get_data().T, delimiter=',', header=header)
dfXX = pd.read_csv('new_name.csv')

in the code_week.ipynb is the same code step by step with several examples. (it was my 4th week in python)

This work continued to be deepened privately, but I can gladly help you with whatever you need.

**Comment by YANKT** [comment]
> 嗨汉克特！
> 
> 我很抱歉文档的不当之处，我开始使用 github 和 python。
> 
> 关于查询，数据集在这个页面上： [https ://physionet.org/content/chbmit/1.0.0/](https://physionet.org/content/chbmit/1.0.0/)
> 
> 这些文件是 .edf 格式，要将其转换为 csv，您必须使用 mne 库。函数 read_raw_edf(XXX.edf) 然后： header = ','.join(edfXXX.ch_names) dfXX = np.savetxt('new_name.csv', XXX.edf.get_data().T, delimiter=',', header =header) dfXX = pd.read_csv('new_name.csv')
> 
> 在 code_week.ipynb 中是相同的代码一步一步的几个例子。（这是我在 python 的第 4 周）
> 
> 这项工作在私下继续深化，但我很乐意为您提供任何您需要的帮助。



> Hi Hankt!
> 
> I am sorry for the impropriety of the document, I was starting to work with github and python.
> 
> Regarding the query, the dataset is on this page: https://physionet.org/content/chbmit/1.0.0/
> 
> The files are in .edf format, to convert it to csv you have to use the mne library. function read_raw_edf(XXX.edf) then: header = ','.join(edfXXX.ch_names) dfXX = np.savetxt('new_name.csv', XXX.edf.get_data().T, delimiter=',', header=header) dfXX = pd.read_csv('new_name.csv')
> 
> in the code_week.ipynb is the same code step by step with several examples. (it was my 4th week in python)
> 
> This work continued to be deepened privately, but I can gladly help you with whatever you need.

Thank you very much for your positive reply, which is very helpful to me，my tutor thought your code was worth learning so she made me understand every step of the code,but I am a python novice so I need to consult you ^_^ .
1.In the Py file CNN_Test.py, whether the code flow reads the data set and divides it into matrix form,then CNN model is created for convolution?
2.What is the function of the CNN1_sz.h5 file saved last, I see it is not used.
3.In the original paper, the code of autoencoder and channel selection algorithm is in which file？
4.rnn-test.py and rnn_test.py which one is the reproduction of CNN LSTM in the original paper

**Comment by Morilla123** [comment]
1. a simplified analysis, I would like to do better, maybe in these weeks I will try to do better.
 edf -->csv--> Crop equal sections in seizure and non-seizure time, You see that in the patient summary --> create the labels --> one hot encoder --> vectorized streide (convert a 23 channel, total length of the sample, in windows of 5 seconds * 256 (sampling frequency), 23 channels --> split train test --> fit model --> results (the metrics are very bad because I only use a very small percentage of data )

2. It does not have a function, it stores the weights of the network, but it was a test. it has no function.

3. I couldn't make the encoder code, the original paper doesn't have much information and I couldn't replicate it. but it seems like a great idea

4.I think it's the same only my computer couldn't process the training so I used google's virtual machines. But I did this a long time ago. I would like to resume it, would you like us to start a new project in collaboration to replicate the paper? It would be really useful. Would you like to talk in Discord? Or something similar. Let me know if you're interested.

**Comment by YANKT** [comment]
Thank you very much for your invitation, and I am glad to cooperate with you. However, I have been under great pressure in scientific research recently. In China, master's students must issue SCI papers to graduate, so I have to focus on my own simulation experiment. This is my wechat: quintinYan , you can communicate with me at any time :)

**Comment by Morilla123** [comment]
Perfect! we have recently resumed this project and will be happy to let you know when we have better reviewed the documentation and code. I understand perfectly what you are saying about being under pressure, please do not hesitate to ask, I am very sorry for the disorder of the code and the impropriety. Surely we will communicate later, this week I will try to make the code much clearer and cleaner

**Comment by YANKT** [comment]
I am looking forward to your good news. Thank you for helping me these days :)
